name: nextflow-kraken2
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.6
  - fastp
  - kraken2=2.1.1
  - multiqc=1.10
  - bracken=2.6.0
  - kaiju=1.7.4
  - krona
  - pandoc
  - r-base
  - r-data.table
  - r-dplyr
  - r-tidyr
  - r-dt
  - r-d3heatmap
